apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/devpathai/devpath-admin
  newName: ghcr.io/devpathai/devpath-admin
  digest: sha256:17c436e073aa57c00043585e0ee85dfeef01a8be9c4f9781b338441365557f15
