apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/devpathai/devpath-admin
  newName: ghcr.io/devpathai/devpath-admin
  digest: sha256:4c93a2859e28240706759d032b0b028a15a04330b04c0c9e0e3f63eea2c6c63e
