apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-admin
  newName: ghcr.io/devpathai/devpath-admin
  newTag: 7633705d30ca7c8b60c46a76ccb0eff2c5ac671a
