apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: devpath-web-staging-default-deny
spec:
  podSelector:
    matchLabels:
      app: devpath-web-staging
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: devpath-web-staging-ingress
spec:
  podSelector:
    matchLabels:
      app: devpath-web-staging
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
    ports:
    - protocol: TCP
      port: 8080
