apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-community-svc
  newName: ghcr.io/devpathai/devpath-community-svc
  newTag: 716076b113f1182fa131c04012134dd0ab5f5e5b
