apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-community-svc
  newName: ghcr.io/devpathai/devpath-community-svc
  newTag: d2b9dc5c3b8b3e6a670fba5b7afcd60735e146dc
