apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-ai-svc
  newName: ghcr.io/devpathai/devpath-ai-svc
  newTag: 19cf7cd7a45ed0b0830ac09b95d4c02d7752f64f
