apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-ai-svc
  newName: ghcr.io/devpathai/devpath-ai-svc
  newTag: d5a52379322d2e0bddef66c5a676eb2e95a8d8d4
