apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-ai-svc
  newName: ghcr.io/devpathai/devpath-ai-svc
  newTag: 8c2cb8df1481d23fe4a82d0ea0ba3879a98abe3e
