---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-claude
  namespace: devpath
spec:
  encryptedData:
    anthropic-api-key: AgAoQHj6oz7qRPwE7MGuQOI5LJxeH5ZAJqwZOWAIQ00V6eyOrudEwwB05YrrvYHdS4vkJU3SFpYx8cI9yn2AffQz8BXNzKIkgY50NV+K862cg+JsJ4vlymKIur7D8EZxYPvuG2P15H2tGhSTzpwjrH1249SFcrgHR6HdzF9ABKI9RvPB/Ufz+XpZiAJKuE+DvS6rpEjkm04D9rdyXRPMIhIVwqc0O7jv7PGe+leJe3Q3Q9VbDtR1uJ97F8vgXHlZVEYmi+EPeTbod0D83TWGHXqmzKG7KTotG4HAw0MecHuCdd36YHtnSOrOMRLAAioKv7XBUHhO7WSpK19w3jva9T140kXxpvTebze4X3rs8jD7opxFKnHrOOaPFvDG2sAZWIvp9wvF5LWzHRBXWxd/8LKTESI5Zg3a3vFYUp/QPP8EZqIT4p5B83HQeYA5GUdhln/LrqqcvHQtTUVy+HdIp5EgKF1qsCOMBsflnTj38sjHpKGuLFMZxyZ59awWy9W3Gi8/ESXWyLBDhJDuW7EfvHG7j+Ex+7wYIdBWslBkfe+s/nujHU5jlRZICazKKDGQ4xqKALYnzPmhCKjHc9FB1c/Gbu91qKJYdUVd19IEellJ4QS4RJNeDYE15RY6Inn0qh1+j0P1t0dxXh7ftOk5emIjiI93DP8UW54xGy3eBRJvr6c4rSx7tYRtx6Pad2tuztIzM3yKyOe6XbgnFeAQB9i/OGI+UPpqf6JNG+ajssXm3rGl7tiiUqhn69wICZJC5qxLWYbQB97iqhkcaSQc9z5Mj64wRYlg+xX8XM71MYBiZsIJkJAqm0Nqo68l5iTqG0h4DuTjrJX04Zpuxbyb
  template:
    metadata:
      creationTimestamp: null
      name: ai-claude
      namespace: devpath
