---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-claude
  namespace: devpath
spec:
  encryptedData:
    anthropic-api-key: AgAGJBHUC56fztxRRF7ppw1ytctSwyBPtRsL74ENPe6ZigZVZycw2WXWlkVPtHMzwvKyKkW5MwBibcTjw0F0gH2fwGJ8zdHlcgVLuyhMYjUZekQ7QZZvstXbs2RW5xo7vs+86s2HDTNMmA48zvdlf+E09tdWYZgkGvvKWwqqKPWRiAk2zL7f0M1WzmahqBLr2swpp8dns8XbUteNulaUObyB3agas2E8YGoXSNELLuObm74YCmmjUgjwFSXqvM+QmJdRvPLwN3HFRLLhnJ3kM83rtiyaBSV0S8cjuWt21vqRFQkaomX2pQsTC8Asx5/TQk06was5ZORC9MQNW0/Mx16PF/ZOD1oKz/rxvRXvjLjHMMMX5Fp46G1gIE0uwwggFK+pQT8QTxlqt7Sp673kBDG/fVWz09D5kAomJkX8GuOenkOnDpuFI7sTXqFnPqs/MqUIv8D9BrdGDETe/tfZ2J+CyuUCYtlC06CwEif+uOHAD+ueksBgHFlsEiWZh6xwLo2NZchXqrWc1wZEOAwGmCkb3UZZ8D0iamSrq1x1WtxCZAMUVIbSS8Yl0mKM4Y+TaCLBGjwFyAzvF2BqVsuahmIxvKoml/ExQllTyyCog8FdHh9Uva5BoNgGJdr6dyH9QnMmolcRKx/4LRo06Nzx1F+w7g41vofcZ+be32OCJ/p1TlUvFxHKuC0WB7z+bkoZzIxooMhhzY8XBjmWnPgdHBO2KuGUzgkRZUBkYVq4t8sr7fnXw55vF8eyVqyIJ7wKbLTi5+FJMaGVr5Eno12s1y0TSe5qNC6fXCoeXmox/jml50ag1WYKj5A3ksDj8rr2Q9wr2Y1bDuRYbV28pmA=
  template:
    metadata:
      creationTimestamp: null
      name: ai-claude
      namespace: devpath
