apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-lcs-svc
  newName: ghcr.io/devpathai/devpath-lcs-svc
  newTag: main
