apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-learning-svc
  newName: ghcr.io/devpathai/devpath-learning-svc
  newTag: 04cc3ee69a78d3f80e258f032082dbf3f8b08a17
