apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-learning-svc
  newName: ghcr.io/devpathai/devpath-learning-svc
  digest: sha256:708b8792dd1e0f4f42d0fe0f15b8a7ae423d3268f9c8123196b6b77ba1658fd0
