apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-learning-svc
  newName: ghcr.io/devpathai/devpath-learning-svc
  newTag: bbcaaaafce867ede818e7dd297732be7fe1c2f57
