apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
- sandbox-preflight.yaml
- writer-fence-rbac.yaml
images:
- name: ghcr.io/devpathai/devpath-migration
  newName: ghcr.io/devpathai/devpath-migration
  newTag: 9793b8f92f92cca1ef57e28d2db6fb7d911741a3
