apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-notification-svc
  newName: ghcr.io/devpathai/devpath-notification-svc
  newTag: c659b215e76d8d59eed772df31d81d9b3e7a9f63
