apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-notification-svc
  newName: ghcr.io/devpathai/devpath-notification-svc
  digest: sha256:e9ae478517c5e0557a268734f3a91dd4ad0a733e8bace1d248b12d417ff6014f
