apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-platform-svc
  newName: ghcr.io/devpathai/devpath-platform-svc
  newTag: 955d012441870e5481170724e1ba5881f93e49c7
