apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- sealedsecret-db.yaml
- sealedsecret-jwt.yaml
- sealedsecret-oauth.yaml
- sealedsecret-mentor-access.yaml
- sealedsecret-turnstile.yaml
- sealedsecret-public-support.yaml
images:
- name: ghcr.io/devpathai/devpath-platform-svc
  newName: ghcr.io/devpathai/devpath-platform-svc
  digest: sha256:29bcc284b42faa8c936eef146a6587c614ad87ba60d3e0d8b0bf2e2336a10494
