apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-platform-svc
  newName: ghcr.io/devpathai/devpath-platform-svc
  newTag: 3f7067f1c965de1f4eeccf7528be728759687d51
