---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mentor-access
  namespace: devpath
spec:
  encryptedData:
    invite-code-hmac-secret: AgB53ht7r2SofYDzze08GlqCn8Nj6NMwqp+PJGIVDKe/W8/aacl0bqB8yoOddp2N8wAvolpwNnTt6e7m0z7GYaNieshMwI0UMhJORXV5RoG5zIBZvitkDQKq+YC2wa0yDxmVyqQPlnKcFs2aF2LuVcTCQV3cCURCJ5rkTTR7u9gpZnpEl8yr2q1y3TRDSBnnMJikebyD0qWeU2O1IiuiOhHt/6/jTXw9dyVjy2v9RW9TIDlx63WWuQuNV2jkQiwE7FXBpNVr236ssbR9VQvhF2eAnEWMi/P9fFxJAx2HLK8bUr1kfIjiw6+dFRWYcsZD3CLftxw2Wx3fvU/jMfK7aoHxBHuRFoo35hrMz6IyQtfKOjlzoM61T5L7SSjaZsOuctJvf53jLYoVLpQE2NCTB0+MWIjVk6t63iOpsOtKbxv0TGEshRNtpPcHQAL5YYKrDGQuvyXMC9BVrczv9sdr+rXmzzSdSbZqW7kvz2BkTupGuxQuy7NIwOjXmz3Jx8/WMTd2dqXC3Lypi48k9YLFZiywDGTA3fGH27rX/XM6tetArDjYG19MVGO27NyuUQn8/kH8kxT3VUonTDTmdaAtG+DiKGspDeL6fB8SLUA4U8R59FOiPV50zJc7jAqE5ulM9XgWSfIeDzwagNwCxtDDQCJ+D9LxdiMUqMmk/mKEmNmVfWjwdb6Ry5kaEbbaN0prVNtaYshu0EwolejkQ94xvU+0kPHp0MVY0QKAHXB2LzU6lMerPtVA0I/lKc+AXQZ14/Q7tRkrbv6i+2XlSeAVb1x/
  template:
    metadata:
      creationTimestamp: null
      name: mentor-access
      namespace: devpath
