---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-turnstile
  namespace: devpath
spec:
  encryptedData:
    turnstile-secret: AgCH3Ug2ql6qUiXtZ0UQEJnl5e4BXbFZVeW9bMRXIBFR5dChgOY40ONB6sV6QR3QyCnXjlAak7Xd+xaL5cp+Kk7s5Iq4MBnh2I8azVXKzvxvAWNhRWw2wttpzDQ1p8K+vFoWMv06INoL7N+CBCxn1WPeHNtfyzqX8KGnpFtfyh1xWZhCsUkn0A2vvMJb4Ep2kMlNgx+wcTWCAvGE1r5t3xKJ5IatwaqmmzCyzjo4oc0tRRiE0iu7IYq0e5CatSZH4JqYqby3HtIaWVWz9Ph2vnmjfCEvHsgDtDhAjow9ZV/2x6hFNIXTTf/IlDJHacl5N0oHAp6M+MGgqvYA9LCrc9QZFGMKtc+91GFmxKBhuINP088fJWm6tGal9GL0U2KOnsSWCeHuc7O66ekTh+ESzx0k49pLR0zMgO+468gKTMv5tMBwMvP9a2/n3vWdSo9BJZNtzuLYhkjhG6egdqWgcW9YmiRjOIdsCeOOHWaA6BpKhHhJu7VsNIwZ/tQpCUlCSGIxAadFU1eE0bcJQNQCYibUZ8JJYxAQbF0KqVDXFJ2EceOpAg0EQVnz9i5+EFuWGFr8GICeNO6AYfaBhYDadgf7DnBGwdO3hlineVh//4SNLBSHeed+GhiyxogPgF5FZ5isLSMp/kYD2Mo7PmYst2v4cBbMYaRLoRAN6yCIN2FSOXS9S6RxcePZtlOIacpn+cX/6a59zMGy7etkIV6S2EJHZCle4cxKTgFSSiUsyX1gqW/O/w==
  template:
    metadata:
      creationTimestamp: null
      name: platform-turnstile
      namespace: devpath
