apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-public-support
  namespace: devpath
spec:
  encryptedData:
    rate-limit-hmac-secret: AgCXkIuNNtb7pxlthZp2SEGHB5ZdY4JqZxMnpV2INZlHfuCVQuAsfz8wEtI1LR93msgsz9PQmDp9kstKGM0qY+EVMWDwi0zbgomWkGAzmDJ9TEqyA1JqSx8mO2sbGt9ElgoV8Dr7KqL/gQc7g0kiDPl3l1i9W6W5+t2vklxIEYPrkFbpMP7ji2pMmpyBUl7hnRUNdMnofu0Ne6T6WqDcqoJHLs5j0nJxEoY+ERnwiy+0fh4HhG9LJIgxTALyAJhP1ilajU4QbJu0S9spvfrtua9bu2SVklpReCxYlLCdpaRa8/XbIAQ8MRzcBsd2dhz8xwofaCLoH2AXvW2KH0f7DYOI3yAMCKSZZRayrAYKvIDavza/rEhRpYGJ2lnDwacxTDGgbCOxvZfAOi6nwCRypySa42V8B0U5L0gPkaDntToJDxmSZ7/91tpncsugcZet/6demNbkQ+xQcO/+DZCSBazjgslp1GYaB6cCaNAcgn+usLO8JN5JgLNONxWEeBdYeFmq4MNZCrRyAnj4Xp8HDANkbzLH/G/nMGHrxDs688+R7cEYvF7k/kbLMjA03PjxPvN1ggLKxpLufx3i+0BLv6Y6Kq7pKz5zUcqBuNk9R32MY7eejjkKfChkFfJr6tqchLJd956Iiwg6PaZhBpt9sLfn9bqPazVuGCKlRJgSgMWcr1doVzx6elFdqMm9m88KJispyNoQmFjXKv/DWDMwuJYY0bUvquyWyyNm98jLr6lDaJkd6xKgyRhDnTQQEF2shsr09LRyhoyURiL37ZpYStCO
  template:
    metadata:
      name: platform-public-support
      namespace: devpath
