---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devpath-jwt
  namespace: devpath
spec:
  encryptedData:
    jwt-secret: AgAaTPXk7RWOdvlSSDSWZqwCEN3/oTpi6xr90fyt7Ekzb/jSXWJt10c4yOKSZC+PTfxsuiSaTBNy68nJV4vpenriRjM8OKfO4WsmWa9EfW3DP4wwUDH9CR8164ysnRntbIdDKKXUCGsk25/m72tbs0WaNaeuNdwNFLys4k7azfazweHnCYnqbsem5OFR3KTcZSgfkFIKhoko2cwpBhZrNEbYoh0MiAFKm4tePRk6/hTB5b2wF0r1nVh0yJb6pfGCygrLcJ3A2GZsehqQY9gAlqrRGGiXllIM5hDs+RKuZv9jUZqNaq09Y140S4sR5HxZUzxtUFlEHv9lBrdYDR9cWu2zr43dPnHmRN9I0+nYXaXoSO2m2tYifs1Vu5WuLh8MZ0xDyGVJ9e/hZunefjVy+FFDLlCn/hAJjzC4LgZWutBcbpkWt97DYG/sqsU+Q9c+72GVE7F8FEYup+6hlXulvpNL1pUXa2BTAZfty+3FE2VOD9bPAbbBx0jvp6cIWUmsTza2g+4a4YpzgW+XCX5TnWZkdspLUsusOpk7Ta2MAT7Zz2+6DZ9e5nMj1ZabF8Wjdozx4/1zvPYGD8J2trpkZ4s222k9dJ44fr0cIht4Pie7kiXjybw45QwySx0sjvcXVj5HqSb2F2jqr6X2bqRVhxtf/wFAtrSIWjz0B++uLk8lAqkbxKQtPvKSS31V+v+oBJCiaIKKgSCyNmXXV2gNMtqUnv6+O9UsnElSRWuLivjGt7VgTFoc82JebV6RGscAVqF3a9JZEZIJp9HCta4lhfhR
  template:
    metadata:
      creationTimestamp: null
      name: devpath-jwt
      namespace: devpath
