apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-gateway
  newName: ghcr.io/devpathai/devpath-gateway
  newTag: 973c72cd371dae364cd82c8e956256b6613cc52a
