apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-gateway
  newName: ghcr.io/devpathai/devpath-gateway
  newTag: 5e3932fc89439a74f8482d94629601a62675efca
