apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- networkpolicy.yaml
images:
- name: ghcr.io/devpathai/devpath-sandbox-svc
  newName: ghcr.io/devpathai/devpath-sandbox-svc
  newTag: bf9ad1ad2a1d03172a9e8a2e17760994ac13f5d7
