apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/devpathai/devpath-sandbox-svc
  newName: ghcr.io/devpathai/devpath-sandbox-svc
  newTag: 6a9e2e401db497640c0a2177f78a926fbf9bc2dd
