apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
images:
- name: ghcr.io/devpathai/devpath-migration
  newName: ghcr.io/devpathai/devpath-migration
  newTag: daece49c9abc812696153711c7d81357fee4eb52
