apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
images:
- name: ghcr.io/devpathai/devpath-migration
  newName: ghcr.io/devpathai/devpath-migration
  newTag: 2e178e809b2d78a5511ff7fd8836b7733f1b8bf1
