apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
images:
- name: ghcr.io/devpathai/devpath-migration
  newName: ghcr.io/devpathai/devpath-migration
  newTag: f85b4df8260de6a0eb99b212cc6a67ba288d1a79
