apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devpath-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: app.leva.ai.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devpath-web
                port:
                  number: 80
  tls:
    - hosts:
        - app.leva.ai.kr
      secretName: devpath-web-tls
